export const SET_FULLPEOPLE_ITEM = "SET_FULLPEOPLE_ITEM";
export const GET_FULLPEOPLE_ITEM = "GET_FULLPEOPLE_ITEM";
export const SET_REQUESTSTATUS = "SET_REQUESTSTATUS";
export const SET_ID = "SET_ID";
